Repository BuffettCode/buffett-code-api-client-excel, pull requests merged in 2021-11, with the labels that each got.

#39 Add api error handling
  BuffettCodeExcelFunctions/UserDefinedFunctions.cs
Labels: enhancement

#40 Skip ondemand check for indicator call
  BuffettCodeIO/ApiTaskHelper.cs
  BuffettCodeIOTests/ApiTaskHelperTests.cs
Labels: bug

#41 Bump version to 1.0.1.2
  BuffettCodeExcelAddin32Installer/Bundle.wxs
  SetupAddinRibbon32/Product.wxs
  SetupExcelFunctions32/Product.wxs
Labels: Installer

#42 Change endpoint selection logic
  BuffettCodeExcelFunctions/ApiResourceFetcher.cs
Labels: enhancement

#43 Bump version to 1.0.1.3
  BuffettCodeExcelAddin32Installer/Bundle.wxs
  SetupAddinRibbon32/Product.wxs
  SetupExcelFunctions32/Product.wxs
Labels: Installer

#46 release 1.0.1.4
  BuffettCodeExcelAddin32Installer/Bundle.wxs
  SetupAddinRibbon32/Product.wxs
  SetupExcelFunctions32/Product.wxs
Labels: release

#48 refactoring ApiClient
  BuffettCodeAPIClient/ApiClientFactory.cs
  BuffettCodeAPIClient/ApiClientInstanceGetter.cs
  BuffettCodeAPIClient/BuffettCodeAPIClient.csproj
  BuffettCodeAPIClient/BuffettCodeApiV2Client.cs
  BuffettCodeAPIClient/BuffettCodeApiV3Client.cs
  BuffettCodeAPIClientTests/ApiClientCoreWithCacheTests.cs
  BuffettCodeAPIClientTests/ApiClientFactoryTest.cs
  BuffettCodeAPIClientTests/ApiClientInstanceGetterTests.cs
  BuffettCodeAPIClientTests/ApiClientTestHelper.cs
  BuffettCodeAPIClientTests/BuffettCodeAPIClientTests.csproj
  BuffettCodeAPIClientTests/BuffettCodeApiV2ClientTests.cs
  BuffettCodeAPIClientTests/BuffettCodeApiV3ClientTests.cs
  BuffettCodeAPIClientTests/ErrorMockApiClientCore.cs
  BuffettCodeAPIClientTests/MockApiClientCore.cs
  BuffettCodeIO/BuffettCodeApiTaskProcessor.cs
Labels: refactoring

#57 Error handling とユーザへの出力を充実させる
  BuffettCodeAPIClient/ApiClientCore.cs
  BuffettCodeAPIClient/ApiGetRequest.cs
  BuffettCodeAPIClient/ApiGetResponseValidator.cs
  BuffettCodeAddinRibbon/BuffettCodeAddinRibbon.csproj
  BuffettCodeAddinRibbon/CsvDownload/CsvDownloadExceptionHandler.cs
  BuffettCodeAddinRibbon/CsvDownload/TabularWriterBuilder.cs
  BuffettCodeAddinRibbon/CsvDownloadForm.cs
  BuffettCodeCommon/BuffettCodeCommon.csproj
  BuffettCodeCommon/BuffettCodeExceptionFinder.cs
  BuffettCodeCommon/Exception/AggregationNotFoundException.cs
  BuffettCodeCommon/Exception/BuffettCodeApiClientException.cs
  BuffettCodeCommonTests/BuffettCodeCommonTests.csproj
  BuffettCodeCommonTests/BuffettCodeExceptionFinderTests.cs
  BuffettCodeExcelFunctions/UserDefinedFunctions.cs
Labels: enhancement
